# runfile is a special function avalable in the pycharm python console
runfile("example01_hello_world.py", wdir=".")
runfile("example01_hello_world_alt_syntax1.py", wdir=".")
runfile("example01_hello_world_alt_syntax2.py", wdir=".")
runfile("example02_kwargs.py", wdir=".")
runfile("example03_inputs.py", wdir=".")
runfile("example03_inputs_parameterization.py", wdir=".")
runfile("example04_outputs.py", wdir=".")
runfile("example04_outputs_parameterization.py", wdir=".")
runfile("example05_files.py", wdir=".")
runfile("example05_files_parameterization.py", wdir=".")
runfile("example06_branch_task.py", wdir=".")
runfile("example06_branch_task_parameterization.py", wdir=".")
runfile("example07_branch_dag.py", wdir=".")
runfile("example07_branch_dag_parameterization.py", wdir=".")
runfile("example08_add_workflow_definition.py", wdir=".")
runfile("example09_add_workflow_definition.py", wdir=".")
