# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2020-08-26T10:40:48+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class Account(BaseModel):
    uuid: Optional[str] = Field(None, title='unique identifier')
    organization_name: Optional[str] = Field(None, title='organization name')
    organization_id: Optional[str] = Field(
        None, title='the official registration number of the organization'
    )
    projects: Optional[List[str]] = Field(
        None, title='the projects owned by this account, by uuid'
    )
    users: Optional[List[str]] = Field(
        None, title='the users who are a member of this account, by uuid'
    )


class Run(BaseModel):
    state: Optional[str] = Field(None, title='state of the singletask run')
    ended_utc: Optional[str] = Field(
        None, title='timestamp of when the workflow ended, in ISO-8601 datetime format'
    )
    traceback: Optional[str] = Field(None, title='detailed error message')
    traceback_raw: Optional[str] = Field(
        None, title='unformatted, detailed error message'
    )
    error_message: Optional[str] = Field(None, title='summarized error message')


class SingleTask(BaseModel):
    id: Optional[str] = Field(None, title='unique identifier of the task')
    name: Optional[str] = Field(None, title='non-unique name of the task')
    updated_utc: Optional[str] = Field(
        None, title='timestamp of the latest change, in ISO-8601 datetime format'
    )
    state: Optional[str] = Field(None, title='current state of the task')
    created_utc: Optional[str] = Field(
        None,
        title='timestamp of when the task was created, in ISO-8601 datetime format',
    )
    runs: Optional[List[Run]] = Field(
        None, title='list of results from running this task'
    )
    definition: Optional[Dict[str, Any]] = Field(None, title='definition of the task')


class SingleTaskSummary(BaseModel):
    id: Optional[str] = Field(None, title='unique identifier of the task')
    name: Optional[str] = Field(None, title='non-unique name of the task')
    updated_utc: Optional[str] = Field(
        None, title='timestamp of the latest change, in ISO-8601 datetime format'
    )
    state: Optional[str] = Field(None, title='current state of the task')


class StorageType(Enum):
    AZURE_BLOB_CONTAINER = 'AZURE_BLOB_CONTAINER'
    LOCAL_FILESYSTEM = 'LOCAL_FILESYSTEM'
    S3_BUCKET = 'S3_BUCKET'


class User(BaseModel):
    username: Optional[str] = Field(None, title='unique username')
    uuid: Optional[str] = Field(None, title='unique identifier')
    accounts: Optional[List[str]] = Field(
        None, title='the accounts the user has access to, by uuid'
    )
    projects: Optional[List[str]] = Field(
        None, title='the projects the user has access to, by uuid'
    )
    given_name: Optional[str] = Field(None, title="the user's given name")
    family_name: Optional[str] = Field(None, title="the user's family name")
    email: Optional[str] = Field(None, title="the user's email address")
    phone_number: Optional[str] = Field(None, title="the user's phone number")


class UserSummary(BaseModel):
    username: Optional[str] = Field(None, title='unique username')
    uuid: Optional[str] = Field(None, title='unique identifier')
    accounts: Optional[List[str]] = Field(
        None, title='the accounts the user has access to, by uuid'
    )
    projects: Optional[List[str]] = Field(
        None, title='the projects the user has access to, by uuid'
    )


class ValidationError(BaseModel):
    loc: List[str] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')


class Workflow(BaseModel):
    id: Optional[str] = Field(None, title='unique ID of the workflow')
    name: Optional[str] = Field(None, title='non-unique name of the workflow')
    project_uuid: Optional[str] = Field(None, title='project that owns this workflow')
    updated_utc: Optional[str] = Field(
        None, title='timestamp of the latest change, in ISO-8601 datetime format'
    )
    user_uuid: Optional[str] = Field(None, title='user that created this workflow')
    state: Optional[str] = Field(
        None, title="current aggregated state of the workflow's tasks"
    )
    created_utc: Optional[str] = Field(
        None,
        title='timestamp of when the workflow was created, in ISO-8601 datetime format',
    )
    task_links: Optional[Dict[str, Any]] = Field(
        None, title='links between tasks in the workflow'
    )
    root_tasks: Optional[List[int]] = Field(None, title='root task(s) of the workflow')
    task_states: Optional[Dict[str, Any]] = Field(
        None, title='current state of each task'
    )
    file_list: Optional[List[Dict[str, Any]]] = Field(
        None, title='list of input and output files for the workflow'
    )
    context_id: Optional[str] = Field(
        None, title="reference to the Workflow's context object"
    )


class WorkflowSummary(BaseModel):
    id: Optional[str] = Field(None, title='unique ID of the workflow')
    name: Optional[str] = Field(None, title='non-unique name of the workflow')
    project_uuid: Optional[str] = Field(None, title='project that owns this workflow')
    updated_utc: Optional[str] = Field(
        None, title='timestamp of the latest change, in ISO-8601 datetime format'
    )
    user_uuid: Optional[str] = Field(None, title='user that created this workflow')
    state: Optional[str] = Field(
        None, title="current aggregated state of the workflow's tasks"
    )


class HTTPValidationError(BaseModel):
    detail: Optional[List[ValidationError]] = Field(None, title='Detail')


class Project(BaseModel):
    uuid: Optional[str] = Field(None, title='unique identifier')
    name: Optional[str] = Field(None, title='organization name')
    account_uuid: Optional[str] = Field(
        None, title='the project owner account, by uuid'
    )
    storage_type: Optional[StorageType] = None
    storage_identifier: Optional[str] = Field(
        None, title='Name or equivalent within the given storage_type'
    )
    external_reference: Optional[str] = Field(
        None, title='a reference number or code this project uses in other systems'
    )
    users: Optional[List[str]] = Field(
        None, title='the users who are a member of this account, by uuid'
    )
